---
count: 4
default:
  restart: 0
  wait: 1
editor:
  files:
    main:
      - lib/File/CodeSearch.pm
      - lib/File/CodeSearch/RegexBuilder.pm
    helpers:
      - lib/File/CodeSearch/Highlighter.pm
      - lib/File/CodeSearch/Replacer.pm
name: cs
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    edit: main
  3:
    edit: helpers
  4: []

