---
abstract: 'Search file contents in code repositories'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-CodeSearch
provides:
  File::CodeSearch:
    file: lib/File/CodeSearch.pm
    version: v0.2.0
  File::CodeSearch::Files:
    file: lib/File/CodeSearch/Files.pm
    version: v0.2.0
  File::CodeSearch::Highlighter:
    file: lib/File/CodeSearch/Highlighter.pm
    version: v0.2.0
  File::CodeSearch::RegexBuilder:
    file: lib/File/CodeSearch/RegexBuilder.pm
    version: v0.2.0
  File::CodeSearch::Replacer:
    file: lib/File/CodeSearch/Replacer.pm
    version: v0.2.0
requires:
  Carp: 0
  Clone: 0
  Config::General: 0
  File::Basename: 0
  File::Slurp: 0
  File::Spec: 0
  File::chdir: 0
  IO::Handle: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Path::Class: 0.16
  Pod::Usage: 0
  Readonly: 0
  Scalar::Util: 0
  Term::ANSIColor: 0
  Term::Size::Any: 0
  perl: 5.006
  version: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-CodeSearch
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/File-CodeSearch.git
version: v0.2.0
